# Generated by Django 3.2.14 on 2022-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
                ('celNum', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birthDayDate', models.DateField()),
                ('hasEmigrated', models.BooleanField()),
            ],
        ),
    ]
